---
version: 2
sources:
- name: "itai.retail_analyst"
  database: "itai"
  schema: "retail_analyst"
  tables:
  - name: "ecom_orders"
    quoting:
      identifier: true
    columns:
    - name: "order_id"
      dataType:
        type: "String"
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "order_date"
      dataType:
        type: "Date"
    - name: "order_amount"
      dataType:
        type: "Double"
  - name: "instore_sales"
    quoting:
      identifier: true
    columns:
    - name: "transaction_id"
      dataType:
        type: "String"
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "transaction_date"
      dataType:
        type: "Date"
    - name: "transaction_amount"
      dataType:
        type: "Double"
  - name: "crm_customers"
    columns:
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "signup_date"
      dataType:
        type: "Date"
    - name: "email"
      dataType:
        type: "String"
    - name: "zip_code"
      dataType:
        type: "Bigint"
    - name: "region"
      dataType:
        type: "String"
    - name: "preferred_channel"
      dataType:
        type: "String"
    type: "table"
- name: "danyelle.demo"
  database: "danyelle"
  schema: "demo"
  tables:
  - name: "cx_demo"
    description: "Customer segmentation data indicating the proportion of customers\
      \ within specific categories, aiding in market analysis and strategy development."
    columns:
    - name: "CUSTOMER_FLAG"
      description: "Indicator flag categorizing customers based on specific criteria."
      dataType:
        type: "String"
    - name: "PERCENTAGE_OF_CUSTOMERS"
      description: "Decimal value representing the proportion of customers within\
        \ a specific category."
      dataType:
        type: "Decimal"
    type: "table"
