---
version: 2
sources:
- name: "danyelle.retail"
  database: "danyelle"
  schema: "retail"
  tables:
  - name: "crm_customers"
    quoting:
      identifier: true
    columns:
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "signup_date"
      dataType:
        type: "Date"
    - name: "email"
      dataType:
        type: "String"
    - name: "zip_code"
      dataType:
        type: "Bigint"
    - name: "region"
      dataType:
        type: "String"
    - name: "preferred_channel"
      dataType:
        type: "String"
  - name: "ecomm_orders"
    quoting:
      identifier: true
    columns:
    - name: "order_id"
      dataType:
        type: "String"
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "order_date"
      dataType:
        type: "Date"
    - name: "order_amount"
      dataType:
        type: "Double"
  - name: "instore_sales"
    quoting:
      identifier: true
    columns:
    - name: "transaction_id"
      dataType:
        type: "String"
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "transaction_date"
      dataType:
        type: "Date"
    - name: "transaction_amount"
      dataType:
        type: "Double"
  - name: "email_events"
    columns:
    - name: "email_id"
      dataType:
        type: "String"
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "event_type"
      dataType:
        type: "String"
    - name: "event_date"
      dataType:
        type: "Date"
    type: "table"
  - name: "rfm_segmentation"
    description: "Customer purchase behavior data used for segmentation, aiding in\
      \ targeted marketing strategies and customer relationship management."
    columns:
    - name: "CUSTOMER_ID"
      description: "Unique identifier assigned to each customer."
      dataType:
        type: "String"
    - name: "SIGNUP_DATE"
      description: "Date when the customer registered; Date is in YYYY-MM-DD format."
      dataType:
        type: "Date"
    - name: "EMAIL"
      description: "Email address of the customer for communication."
      dataType:
        type: "String"
    - name: "ZIP_CODE"
      description: "Postal code of the customer's address."
      dataType:
        type: "Bigint"
    - name: "REGION"
      description: "Geographical area where the customer is located."
      dataType:
        type: "String"
    - name: "PREFERRED_CHANNEL"
      description: "The customer's favored method of communication or shopping, such\
        \ as online or in-store."
      dataType:
        type: "String"
    - name: "ORDER_ID"
      description: "Unique identifier for each customer order."
      dataType:
        type: "String"
    - name: "ORDER_DATE"
      description: "The date on which the customer placed the order; Date is in YYYY-MM-DD\
        \ format."
      dataType:
        type: "Date"
    - name: "ORDER_AMOUNT"
      description: "Total monetary value of the customer's order."
      dataType:
        type: "Double"
    - name: "TRANSACTION_ID"
      description: "Unique identifier for each financial transaction."
      dataType:
        type: "String"
    - name: "TRANSACTION_DATE"
      description: "Date when the transaction was made; Date is in YYYY-MM-DD format."
      dataType:
        type: "Date"
    - name: "TRANSACTION_AMOUNT"
      description: "Total amount of money involved in the transaction."
      dataType:
        type: "Double"
    - name: "recency"
      description: "Number of days since the last transaction, indicating how recently\
        \ a customer has transacted."
      dataType:
        type: "Bigint"
    - name: "frequency"
      description: "Total number of transactions made by the customer, indicating\
        \ how often they transact."
      dataType:
        type: "Bigint"
    - name: "monetary"
      description: "Total spending by the customer, indicating the overall value of\
        \ their transactions."
      dataType:
        type: "Double"
    - name: "recency_score"
      description: "Score indicating how recently a customer made a purchase, with\
        \ higher scores for more recent activity."
      dataType:
        type: "Integer"
    - name: "monetary_score"
      description: "Score representing the total spending of a customer, with higher\
        \ scores for greater spending."
      dataType:
        type: "Integer"
    - name: "frequency_score"
      description: "Score reflecting how often a customer makes purchases, with higher\
        \ scores for more frequent transactions."
      dataType:
        type: "Integer"
    - name: "RFM_flag"
      description: "Categorical label derived from RFM analysis, indicating the customer's\
        \ segment based on recency, frequency, and monetary scores."
      dataType:
        type: "String"
    type: "table"
- name: "danyelle.helloworld"
  database: "danyelle"
  schema: "helloworld"
  tables:
  - name: "hw_customers"
    columns:
    - name: "customer_id"
      dataType:
        type: "Integer"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "phone"
      dataType:
        type: "String"
    - name: "email"
      dataType:
        type: "String"
    - name: "country_code"
      dataType:
        type: "String"
    - name: "account_open_date"
      dataType:
        type: "String"
    - name: "account_flags"
      dataType:
        type: "String"
    type: "table"
  - name: "hw_orders"
    columns:
    - name: "order_id"
      dataType:
        type: "Integer"
    - name: "customer_id"
      dataType:
        type: "Integer"
    - name: "order_status"
      dataType:
        type: "String"
    - name: "order_category"
      dataType:
        type: "String"
    - name: "order_date"
      dataType:
        type: "String"
    - name: "amount"
      dataType:
        type: "Double"
    type: "table"
