---
version: 2
sources:
- name: "danyelle.retail"
  database: "danyelle"
  schema: "retail"
  tables:
  - name: "crm_customers"
    quoting:
      identifier: true
    columns:
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "signup_date"
      dataType:
        type: "Date"
    - name: "email"
      dataType:
        type: "String"
    - name: "zip_code"
      dataType:
        type: "Bigint"
    - name: "region"
      dataType:
        type: "String"
    - name: "preferred_channel"
      dataType:
        type: "String"
  - name: "ecomm_orders"
    quoting:
      identifier: true
    columns:
    - name: "order_id"
      dataType:
        type: "String"
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "order_date"
      dataType:
        type: "Date"
    - name: "order_amount"
      dataType:
        type: "Double"
  - name: "instore_sales"
    quoting:
      identifier: true
    columns:
    - name: "transaction_id"
      dataType:
        type: "String"
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "transaction_date"
      dataType:
        type: "Date"
    - name: "transaction_amount"
      dataType:
        type: "Double"
  - name: "email_events"
    columns:
    - name: "email_id"
      dataType:
        type: "String"
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "event_type"
      dataType:
        type: "String"
    - name: "event_date"
      dataType:
        type: "Date"
    type: "table"
  - name: "rfm_segmentation"
    description: "Customer purchase behavior data used for segmentation, aiding in\
      \ targeted marketing strategies and customer relationship management."
    columns:
    - name: "CUSTOMER_ID"
      description: "Unique identifier assigned to each customer."
      dataType:
        type: "String"
    - name: "SIGNUP_DATE"
      description: "Date when the customer registered; Date is in YYYY-MM-DD format."
      dataType:
        type: "Date"
    - name: "EMAIL"
      description: "Email address of the customer for communication."
      dataType:
        type: "String"
    - name: "ZIP_CODE"
      description: "Postal code of the customer's address."
      dataType:
        type: "Bigint"
    - name: "REGION"
      description: "Geographical area where the customer is located."
      dataType:
        type: "String"
    - name: "PREFERRED_CHANNEL"
      description: "The customer's most favored communication or purchase channel."
      dataType:
        type: "String"
    - name: "ORDER_ID"
      description: "Unique identifier for each customer order."
      dataType:
        type: "String"
    - name: "ORDER_DATE"
      description: "The date on which the customer placed the order."
      dataType:
        type: "Date"
    - name: "ORDER_AMOUNT"
      description: "The total monetary value of the customer's order."
      dataType:
        type: "Double"
    - name: "TRANSACTION_ID"
      description: "Unique identifier for each financial transaction."
      dataType:
        type: "String"
    - name: "TRANSACTION_DATE"
      description: "Date when the transaction occurred; Date is in YYYY-MM-DD format."
      dataType:
        type: "Date"
    - name: "TRANSACTION_AMOUNT"
      description: "Total amount of money involved in the transaction."
      dataType:
        type: "Double"
    - name: "RECENCY"
      description: "Number of days since the customer's last transaction."
      dataType:
        type: "Bigint"
    - name: "FREQUENCY"
      description: "Total number of transactions made by the customer."
      dataType:
        type: "Bigint"
    - name: "MONETARY"
      description: "Total amount spent by the customer across all transactions."
      dataType:
        type: "Double"
    - name: "RECENCY_SCORE"
      description: "Score indicating how recently a customer made a purchase, with\
        \ higher scores for more recent activity."
      dataType:
        type: "Integer"
    - name: "FREQUENCY_SCORE"
      description: "Score representing how often a customer makes purchases, with\
        \ higher scores for more frequent transactions."
      dataType:
        type: "Integer"
    - name: "MONETARY_SCORE"
      description: "Score reflecting the amount a customer spends, with higher scores\
        \ for greater spending."
      dataType:
        type: "Integer"
    - name: "RFM_SEGMENT"
      description: "Categorization of customers based on their recency, frequency,\
        \ and monetary scores for targeted marketing."
      dataType:
        type: "String"
    type: "table"
