---
version: 2
sources:
- name: "danyelle.retail"
  database: "danyelle"
  schema: "retail"
  tables:
  - name: "crm_customers"
    quoting:
      identifier: true
    columns:
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "signup_date"
      dataType:
        type: "Date"
    - name: "email"
      dataType:
        type: "String"
    - name: "zip_code"
      dataType:
        type: "Bigint"
    - name: "region"
      dataType:
        type: "String"
    - name: "preferred_channel"
      dataType:
        type: "String"
  - name: "ecomm_orders"
    quoting:
      identifier: true
    columns:
    - name: "order_id"
      dataType:
        type: "String"
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "order_date"
      dataType:
        type: "Date"
    - name: "order_amount"
      dataType:
        type: "Double"
  - name: "instore_sales"
    quoting:
      identifier: true
    columns:
    - name: "transaction_id"
      dataType:
        type: "String"
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "transaction_date"
      dataType:
        type: "Date"
    - name: "transaction_amount"
      dataType:
        type: "Double"
  - name: "email_events"
    columns:
    - name: "email_id"
      dataType:
        type: "String"
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "event_type"
      dataType:
        type: "String"
    - name: "event_date"
      dataType:
        type: "Date"
    type: "table"
